#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Sensor, in2,    lineTracker,    sensorLineFollower)
#pragma config(Sensor, in3,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  limit,          sensorTouch)
#pragma config(Sensor, dgtl2,  button,         sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ultraSonic,     sensorSONAR_inch)
#pragma config(Sensor, dgtl12, LED,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
we are going to write the hello world of robotics.
Blink LED 5 times with 1 second intervals.
*/

task main()
{

	SensorValue[LED] = 1; // turns led on
	wait1Msec(500);			// waits for 1 second
	SensorValue[LED] = 0; // turns Led off
	wait1Msec(500);
	SensorValue[LED] = 1; // turns led on
	wait1Msec(500);			// waits for 1 second
	SensorValue[LED] = 0; // turns Led off



	//turn on a motor to run a direction (cw/ccw)
	motor[leftMotor] = 100;
	wait1Msec(1000);
	motor[leftMotor] = 0;
	wait1Msec (1000);

	//turns servo from position 127 to 0.
	motor[servoMotor] = 100;
	wait1Msec(1000);
	motor[servoMotor] = -127;
	wait1Msec(1000);
}
